import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import QuestionItem from '@/components/QuestionTemplate/QuestionTemplate';
import { Question } from '@/types';
import { type } from 'os';
import { useMultiStepForm } from '@/utils/useMultiStepForm';
import { FormEvent, useState } from 'react';
import { MultiStepForm } from '@/components/MultiStepForm/MultiStepForm';

const inter = Inter({ subsets: ['latin'] });

let questionArray: Question[] = [
  {
    type: 'YN',
    content: {
      question: 'Is door bad?',
    },

    value: "DoorQuality"
  },

  {
    type: 'INPUT',
    content: {
      question: 'How bad the door?',
    },
    value: "DoorInfo"
  },

  {
    type: 'MULTI',
    content: {
      question: 'How many hinge does door own?',
      options: ['seven', 'nine', 'three', 'fourteen'],
    },

    value:"HingeNumber",
  },
];

export default function Home() {

  const [pageAnswer, setPageAnswer] = useState({});

  const onPageAnswerUpdate = (step: any, questionObj: any) => {
    setPageAnswer({...pageAnswer, [step]: questionObj})
  }


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* {questionArray.map((q,index) => {
        return <QuestionItem question={q} key={`question_${index}`}/>;
      })} */}
    <h1 className="text-3xl font-bold underline">
      Hello world!
    </h1>

    <MultiStepForm questionList={questionArray} onPageUpdate={onPageAnswerUpdate} pageAnswers={pageAnswer}/>
    
    </>
  );
}
